# filepath: c:\Users\sahil\OneDrive\Desktop\sgp\SGP_LLM_2025\docker-compose.yml
version: '3.8'

services:
  sgp_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${AIzaSyDi6xnfrLXsQfvEKZUGnPo9W9otrClzjrI} # Pass the API key from your environment
    volumes:
      - .:/app